### ISSUE TITLE
How to generate the utt2spk file and utt2spk file？

### ISSUE THREAD

**Issue by skxooo** [BUTSpeechFIT/EEND#14]
I understand the general purpose of these two files, but I’m still a bit uncertain about how to generate them correctly. For instance, when creating an utt2spk file, does uttid correspond to the filename? And what should the corresponding spkid be? For different speakers, would it be appropriate to use identifiers like spk00, spk01, and spk02? For the second utterance, can I continue using spk00, spk01, and spk02, or would it be better to use new identifiers, starting from spk03?

Additionally, I have a question regarding the spk2utt file. Should speaker IDs be unique within each utterance, or do they need to be unique across the entire dataset?

Thank you very much for your time and assistance—it’s greatly appreciated!

**Comment by skxooo** [comment]
May I ask an additional question: does each utterance correspond to a separate WAV file? Thank you, and I look forward to your response.

**Comment by skxooo** [comment]
Hello,

I have resolved the previous issues by reviewing the Speechocean762 dataset. However, a new problem has come up: how can I obtain the segment file? When building Kaldi data, the absence of the segment file does not cause an error, but it does lead to an error when generating STFT features. Could you please let me know what the format of the segment file should be?

Thank you very much!

**Comment by fnlandini** [comment]
Hi @skxooo

Just in case, I will answer all questions.
The utt2spk maps each of the segments to the speaker of that segment while spk2utt does the opposite: for each speaker is lists all the utterances (speech segments) of that speaker. A single recordings can have several utterances. Note that if a speaker appears in different recordings, spk2utt will list all of them, not just segments from one recording.
This leads to your second question. Ideally, the speaker identifiers should be unique for the whole dataset. If you do not have that information in your set, then it would be better to start using new labels for new recordings.

Regarding the segment file, this one marks the different speech segments in the dataset with the format
```
speaker-id_recording-id_start-time_end-time recording-id start-time end-time
```
where recording-id is the recording name, speaker-id is the identifier of the speaker that spoke that segment. start-time and end-time are the timing details of the segment in seconds for the third and forth columns. As part of the segment-id in the first column, start-time and end-time have 10ms precision and leading zeros so for example start 0.31 and end 2.29 become `000031_000229`

In the recipes I shared in https://github.com/BUTSpeechFIT/EEND_dataprep/tree/main the segments file is obtained running voice activity detection so that is why it is not generated as part of the EEND training code.
If you are generating synthetic data, you can see the EEND_dataprep recipes to see how the VAD is run.
If you have manual annotations, in rttm format, you could try to generate the segments file by manipulating the fields and respecting the expected format.

I hope this helps.
Federico

**Comment by fnlandini** [comment]
Feel free to reopen if you see fit.
